apiVersion: v1
kind: Service
metadata:
  name: my-mongodb-service
  labels:
    app: my-mongodb
spec:
  clusterIP: None
  selector:
    app: my-mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: my-mongodb
    protocol: TCP