apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-mongodb
  labels:
    app: my-mongodb
spec:
  serviceName: my-mongodb-service
  
  replicas: 3
  
  selector:
    matchLabels:
      app: my-mongodb
  
  template:
    metadata:
      labels:
        app: my-mongodb
        tier: database
    spec:
      containers:
      - name: my-mongodb
        image: docker.io/library/mongo:7
        ports:
        - containerPort: 27017
          name: my-mongodb
        
        env:
        - name: DB_NAME
          value: "employees_data"
        
        volumeMounts:
        - name: my-mongodb-storage
          mountPath: mongodb/data/
  volumeClaimTemplates:
  - metadata:
      name: my-mongodb-storage
      labels:
        app: my-mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi